### ISSUE TITLE
Template repository

### ISSUE THREAD

**Issue by dfalbel** [extendr/helloextendr#9]
Can we make this repository a template repository as per: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

> Creating a repository from a template is similar to forking a repository, but there are important differences:
> 
> A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
> Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
> A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly.

From [gh docs again](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template)

**Comment by clauswilke** [comment]
Ok, I believe I just turned this on. Could you check?

**Comment by dfalbel** [comment]
Works great now! Thanks @clauswilke
